import './css/style.css';

import { Inter, Bricolage_Grotesque } from 'next/font/google';
import Theme from './theme-provider';

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
  display: 'swap',
});

const bricolage_grotesque = Bricolage_Grotesque({
  subsets: ['latin'],
  variable: '--font-grotesque',
  display: 'swap',
  adjustFontFallback: false,
});

export const metadata = {
  title: 'Alex Fleurquin',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="fr" className="scroll-smooth">
      <body
        className={`${inter.className} ${bricolage_grotesque.className} antialiased bg-gray-100 text-slate-100 dark:bg-gray-900 tracking-tight`}
      >
        <Theme>
          <div className="flex flex-col min-h-screen overflow-hidden supports-[overflow:clip]:overflow-clip">
            {children}
          </div>
        </Theme>
      </body>
    </html>
  );
}
